# Site settings
title: Welcome to Hayley's Homepage
email: hayleyy321@kaist.ac.kr
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Hayley's homepage. 
  This page includes my CV and personal blog posts about things that I want to talk about. 
  I hope you could find my homepage interesting.
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hayleymol.github.io" # the base hostname & protocol for your site
github_username:  Hayleymol

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "MS Candidate"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
