# Site settings
title: Hello! I am Hayley!
email: hayleyy321@kaist.ac.kr
description: > # this means to ignore newlines until "baseurl:"
  Hello, my name is Taehei Hayley Kim. I am a master student at Motion Computing Laboratory at KAIST.
  I am interested in character animation, especially regarding human motion. I am looking into motion retargeting,
  motion generation and keyframe based motion control. 
  
  I am a person who don't hesitate to persue what I love. My career path proves that. 
  I was originally an asian studies major under anthropology. Encountment with data visualization in journalism 
  started my interest in graphics and visualization which led me to double major in computer science. 
  My specific like for graphics eventually led me into animation field. Since I loved to see natural human movement 
  inside graphics envionment, I chose character animation and human motion as my main field of study.
  I am learning new things everyday and I love the process of me learning new cutting edge technology in my field.
  
  This page includes my CV and personal blog posts about things that I want to talk about. 
  I hope you could find my homepage interesting.
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hayleymol.github.io" # the base hostname & protocol for your site
github_username:  Hayleymol

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "MS Candidate"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
